# Generated by Django 5.1.1 on 2025-01-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.servicecategory'),
        ),
    ]
