# Generated by Django 5.1.1 on 2025-01-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_serviceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Service_name',
        ),
        migrations.AlterField(
            model_name='services',
            name='Service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.servicecategory'),
        ),
    ]
