# Generated by Django 5.1.1 on 2024-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_subscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_months',
            field=models.IntegerField(choices=[(6, '6 months'), (12, '12 months')]),
        ),
    ]
