# Generated by Django 5.1.1 on 2025-01-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_services_rate_alter_services_service_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='Rate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='Service_category',
            new_name='service_category',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='Service_details',
            new_name='service_details',
        ),
    ]
