# Generated by Django 5.1.1 on 2024-11-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
