# Generated by Django 5.1.1 on 2025-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_serviceinteractionlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinteractionlog',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='serviceinteractionlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
