# Generated by Django 5.1.1 on 2024-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
