# Generated by Django 5.1.1 on 2024-11-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_product_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
