# Generated by Django 5.1.1 on 2024-12-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_brand_promoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in months')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
            ],
        ),
    ]
