# Generated by Django 5.1.1 on 2024-12-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='assigned_vendor',
            field=models.CharField(blank=True, help_text='Name of the assigned vendor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='end_date',
            field=models.DateField(blank=True, help_text='Calculated based on duration and start_date', null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='postal_code',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
