# Generated by Django 5.1.1 on 2024-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_remove_subscriber_status_subscriber_assigned_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
