# Generated by Django 5.1.1 on 2024-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0021_alter_vendor_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='location',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='Address',
            field=models.TextField(blank=True),
        ),
    ]
