name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: deploy
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            git pull origin main  # Update with your branch
            source venv/bin/activate  # If using a virtualenv
            pip install -r requirements.txt  # Install dependencies
            python manage.py migrate  # Run migrations
            python manage.py collectstatic --noinput  # Collect static files
            sudo systemctl restart gunicorn  # Restart Gunicorn
            sudo systemctl restart nginx  # Restart Nginx
